In [82]:
import pandas as pd
import numpy as np
import copy
from sklearn.datasets import load_breast_cancer
from sklearn import metrics

In [83]:
# TASK 1 Membaca ( Load ) Dataset
cancer = load_breast_cancer() # Load file dari library
breast = pd.DataFrame(np.c_[cancer['data'], cancer['target']],
                  columns= np.append(cancer['feature_names'], ['target'])) # Converting
print(breast)

tenis = pd.read_csv("Data/play_tennis.csv") # Read csv classic
print(tenis)


     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mea

In [84]:
# SPLITTING FILES 
from sklearn.model_selection import train_test_split # For splitting purpose

breast_train, breast_test = train_test_split(breast, test_size=0.2) # split 0.8 
print("Data Split (80%) for Breast")
print(breast_train)
print("\nData Split (20%) for Breast")
print(breast_test)

tenis_train, tenis_test = train_test_split(tenis, test_size=0.2) # split 0.2
print("Data Split (80%) for Tenis")
print(tenis_train)
print("\nData Split (20%) for Tenis")
print(tenis_test)

Data Split (80%) for Breast
     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
234        9.567         15.91           60.21      279.6          0.08464   
273        9.742         15.67           61.50      289.9          0.09037   
539        7.691         25.44           48.34      170.4          0.08668   
24        16.650         21.38          110.00      904.6          0.11210   
544       13.870         20.70           89.77      584.8          0.09578   
..           ...           ...             ...        ...              ...   
454       12.620         17.15           80.62      492.9          0.08583   
399       11.800         17.26           75.26      431.9          0.09087   
514       15.050         19.07           97.26      701.9          0.09215   
436       12.870         19.54           82.67      509.2          0.09136   
249       11.520         14.93           73.87      406.3          0.10130   

     mean compactness  mean concavi

In [101]:
X_train_breast, X_test_breast, y_train_breast, y_test_breast = train_test_split(cancer.data, cancer.target, test_size=0.2,random_state=2)
train_tenis, test_tenis= train_test_split(tenis, test_size=0.2, random_state=3)

In [117]:
# Algoritma 4 - Logistic Regression
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=2000)

logreg.fit(X_train_breast, y_train_breast)

y_pred_breast = logreg.predict(X_test_breast)
cnf_matrix_breast = metrics.confusion_matrix(y_test_breast, y_pred_breast)

print(cnf_matrix_breast)
print("Accuracy:",metrics.accuracy_score(y_test_breast, y_pred_breast))
print("Precision:",metrics.precision_score(y_test_breast, y_pred_breast))
print("Recall:",metrics.recall_score(y_test_breast, y_pred_breast))
print("F1 Score:",metrics.f1_score(y_test_breast, y_pred_breast))

[[41  4]
 [ 4 65]]
Accuracy: 0.9298245614035088
Precision: 0.9420289855072463
Recall: 0.9420289855072463
F1 Score: 0.9420289855072463


In [102]:
from sklearn.preprocessing import LabelEncoder

train_tenis = train_tenis.copy()
test_tenis = test_tenis.copy()

le = LabelEncoder()
for col in ['outlook', 'temp', 'humidity', 'wind', 'play']:
    train_tenis[col + '_num'] = le.fit_transform(train_tenis[col])
    test_tenis[col + '_num'] = le.fit_transform(test_tenis[col])
    
X_train_tenis = train_tenis[['outlook_num', 'temp_num', 'humidity_num', 'wind_num']]
X_test_tenis = test_tenis[['outlook_num', 'temp_num', 'humidity_num', 'wind_num']]
y_train_tenis = train_tenis['play_num']
y_test_tenis = test_tenis['play_num']

logreg.fit(X_train_tenis, y_train_tenis)

y_pred_tenis = logreg.predict(X_test_tenis)
cnf_matrix_tenis = metrics.confusion_matrix(y_test_tenis, y_pred_tenis)

print(cnf_matrix_tenis)
print("Accuracy:",metrics.accuracy_score(y_test_tenis, y_pred_tenis))
print("Precision:",metrics.precision_score(y_test_tenis, y_pred_tenis))
print("Recall:",metrics.recall_score(y_test_tenis, y_pred_tenis))
print("F1 Score:",metrics.f1_score(y_test_tenis, y_pred_tenis))

[[0 2]
 [0 1]]
Accuracy: 0.3333333333333333
Precision: 0.3333333333333333
Recall: 1.0
F1 Score: 0.5


In [116]:
# Algoritma 5 - Neural Network
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=[8,8,8], max_iter=2000)

mlp.fit(X_train_breast, y_train_breast)

y_pred_breast = mlp.predict(X_test_breast)
cnf_matrix_breast = metrics.confusion_matrix(y_test_breast, y_pred_breast)

print(cnf_matrix_breast)
print("Accuracy:",metrics.accuracy_score(y_test_breast, y_pred_breast))
print("Precision:",metrics.precision_score(y_test_breast, y_pred_breast))
print("Recall:",metrics.recall_score(y_test_breast, y_pred_breast))
print("F1 Score:",metrics.f1_score(y_test_breast, y_pred_breast))

[[40  5]
 [ 6 63]]
Accuracy: 0.9035087719298246
Precision: 0.9264705882352942
Recall: 0.9130434782608695
F1 Score: 0.9197080291970804


In [103]:
train_tenis = train_tenis.copy()
test_tenis = test_tenis.copy()

le = LabelEncoder()
for col in ['outlook', 'temp', 'humidity', 'wind', 'play']:
    train_tenis[col + '_num'] = le.fit_transform(train_tenis[col])
    test_tenis[col + '_num'] = le.fit_transform(test_tenis[col])
    
X_train_tenis = train_tenis[['outlook_num', 'temp_num', 'humidity_num', 'wind_num']]
X_test_tenis = test_tenis[['outlook_num', 'temp_num', 'humidity_num', 'wind_num']]
y_train_tenis = train_tenis['play_num']
y_test_tenis = test_tenis['play_num']

mlp.fit(X_train_tenis, y_train_tenis)

y_pred_tenis = logreg.predict(X_test_tenis)
cnf_matrix_tenis = metrics.confusion_matrix(y_test_tenis, y_pred_tenis)

print(cnf_matrix_tenis)
print("Accuracy:",metrics.accuracy_score(y_test_tenis, y_pred_tenis))
print("Precision:",metrics.precision_score(y_test_tenis, y_pred_tenis))
print("Recall:",metrics.recall_score(y_test_tenis, y_pred_tenis))
print("F1 Score:",metrics.f1_score(y_test_tenis, y_pred_tenis))

[[0 2]
 [0 1]]
Accuracy: 0.3333333333333333
Precision: 0.3333333333333333
Recall: 1.0
F1 Score: 0.5


In [105]:
# Algoritma 6 - SVM
from sklearn import svm

clf = svm.SVC(kernel = "linear")

clf.fit(X_train_breast, y_train_breast)

y_pred_breast = clf.predict(X_test_breast)
cnf_matrix_breast = metrics.confusion_matrix(y_test_breast, y_pred_breast)

print(cnf_matrix_breast)
print("Accuracy:",metrics.accuracy_score(y_test_breast, y_pred_breast))
print("Precision:",metrics.precision_score(y_test_breast, y_pred_breast))
print("Recall:",metrics.recall_score(y_test_breast, y_pred_breast))
print("F1 Score:",metrics.f1_score(y_test_breast, y_pred_breast))

[[42  3]
 [ 3 66]]
Accuracy: 0.9473684210526315
Precision: 0.9565217391304348
Recall: 0.9565217391304348
F1 Score: 0.9565217391304348


In [104]:
train_tenis = train_tenis.copy()
test_tenis = test_tenis.copy()

le = LabelEncoder()
for col in ['outlook', 'temp', 'humidity', 'wind', 'play']:
    train_tenis[col + '_num'] = le.fit_transform(train_tenis[col])
    test_tenis[col + '_num'] = le.fit_transform(test_tenis[col])
    
X_train_tenis = train_tenis[['outlook_num', 'temp_num', 'humidity_num', 'wind_num']]
X_test_tenis = test_tenis[['outlook_num', 'temp_num', 'humidity_num', 'wind_num']]
y_train_tenis = train_tenis['play_num']
y_test_tenis = test_tenis['play_num']

clf.fit(X_train_tenis, y_train_tenis)

y_pred_tenis = logreg.predict(X_test_tenis)
cnf_matrix_tenis = metrics.confusion_matrix(y_test_tenis, y_pred_tenis)

print(cnf_matrix_tenis)
print("Accuracy:",metrics.accuracy_score(y_test_tenis, y_pred_tenis))
print("Precision:",metrics.precision_score(y_test_tenis, y_pred_tenis))
print("Recall:",metrics.recall_score(y_test_tenis, y_pred_tenis))
print("F1 Score:",metrics.f1_score(y_test_tenis, y_pred_tenis))

[[0 2]
 [0 1]]
Accuracy: 0.3333333333333333
Precision: 0.3333333333333333
Recall: 1.0
F1 Score: 0.5
